spring:
  application:
    name: grpc-client
  main:    web-application-type: NONE
        
server:  port: 9090     
  
grpc:
  client:
    grpc-server:
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext