// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: detections.proto

package com.indra.srcc.airsrcc.lib;

public final class Detections {
  private Detections() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DetectionDataRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DetectionDataRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sourceName = 1;</code>
     */
    java.lang.String getSourceName();
    /**
     * <code>string sourceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getSourceNameBytes();

    /**
     * <code>double latitude = 3;</code>
     */
    double getLatitude();

    /**
     * <code>double longitude = 4;</code>
     */
    double getLongitude();

    /**
     * <code>double altitude = 5;</code>
     */
    double getAltitude();

    /**
     * <code>double heading = 6;</code>
     */
    double getHeading();

    /**
     * <code>double speed = 7;</code>
     */
    double getSpeed();

    /**
     * <code>uint32 type = 8;</code>
     */
    int getType();

    /**
     * <code>uint32 origin = 9;</code>
     */
    int getOrigin();

    /**
     * <code>string id = 16;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 16;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string nato_id = 18;</code>
     */
    java.lang.String getNatoId();
    /**
     * <code>string nato_id = 18;</code>
     */
    com.google.protobuf.ByteString
        getNatoIdBytes();
  }
  /**
   * <pre>
   * The request message containing the detection data.
   * </pre>
   *
   * Protobuf type {@code DetectionDataRequest}
   */
  public  static final class DetectionDataRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DetectionDataRequest)
      DetectionDataRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DetectionDataRequest.newBuilder() to construct.
    private DetectionDataRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DetectionDataRequest() {
      sourceName_ = "";
      latitude_ = 0D;
      longitude_ = 0D;
      altitude_ = 0D;
      heading_ = 0D;
      speed_ = 0D;
      type_ = 0;
      origin_ = 0;
      id_ = "";
      natoId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DetectionDataRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sourceName_ = s;
              break;
            }
            case 25: {

              latitude_ = input.readDouble();
              break;
            }
            case 33: {

              longitude_ = input.readDouble();
              break;
            }
            case 41: {

              altitude_ = input.readDouble();
              break;
            }
            case 49: {

              heading_ = input.readDouble();
              break;
            }
            case 57: {

              speed_ = input.readDouble();
              break;
            }
            case 64: {

              type_ = input.readUInt32();
              break;
            }
            case 72: {

              origin_ = input.readUInt32();
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 146: {
              java.lang.String s = input.readStringRequireUtf8();

              natoId_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest.class, com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest.Builder.class);
    }

    public static final int SOURCENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object sourceName_;
    /**
     * <code>string sourceName = 1;</code>
     */
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceName_ = s;
        return s;
      }
    }
    /**
     * <code>string sourceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 3;
    private double latitude_;
    /**
     * <code>double latitude = 3;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 4;
    private double longitude_;
    /**
     * <code>double longitude = 4;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 5;
    private double altitude_;
    /**
     * <code>double altitude = 5;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    public static final int HEADING_FIELD_NUMBER = 6;
    private double heading_;
    /**
     * <code>double heading = 6;</code>
     */
    public double getHeading() {
      return heading_;
    }

    public static final int SPEED_FIELD_NUMBER = 7;
    private double speed_;
    /**
     * <code>double speed = 7;</code>
     */
    public double getSpeed() {
      return speed_;
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private int type_;
    /**
     * <code>uint32 type = 8;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int ORIGIN_FIELD_NUMBER = 9;
    private int origin_;
    /**
     * <code>uint32 origin = 9;</code>
     */
    public int getOrigin() {
      return origin_;
    }

    public static final int ID_FIELD_NUMBER = 16;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 16;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 16;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATO_ID_FIELD_NUMBER = 18;
    private volatile java.lang.Object natoId_;
    /**
     * <code>string nato_id = 18;</code>
     */
    public java.lang.String getNatoId() {
      java.lang.Object ref = natoId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        natoId_ = s;
        return s;
      }
    }
    /**
     * <code>string nato_id = 18;</code>
     */
    public com.google.protobuf.ByteString
        getNatoIdBytes() {
      java.lang.Object ref = natoId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        natoId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSourceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourceName_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(3, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(4, longitude_);
      }
      if (altitude_ != 0D) {
        output.writeDouble(5, altitude_);
      }
      if (heading_ != 0D) {
        output.writeDouble(6, heading_);
      }
      if (speed_ != 0D) {
        output.writeDouble(7, speed_);
      }
      if (type_ != 0) {
        output.writeUInt32(8, type_);
      }
      if (origin_ != 0) {
        output.writeUInt32(9, origin_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, id_);
      }
      if (!getNatoIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 18, natoId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSourceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourceName_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, longitude_);
      }
      if (altitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, altitude_);
      }
      if (heading_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, heading_);
      }
      if (speed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, speed_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, type_);
      }
      if (origin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, origin_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, id_);
      }
      if (!getNatoIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, natoId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest)) {
        return super.equals(obj);
      }
      com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest other = (com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest) obj;

      boolean result = true;
      result = result && getSourceName()
          .equals(other.getSourceName());
      result = result && (
          java.lang.Double.doubleToLongBits(getLatitude())
          == java.lang.Double.doubleToLongBits(
              other.getLatitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getLongitude())
          == java.lang.Double.doubleToLongBits(
              other.getLongitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getAltitude())
          == java.lang.Double.doubleToLongBits(
              other.getAltitude()));
      result = result && (
          java.lang.Double.doubleToLongBits(getHeading())
          == java.lang.Double.doubleToLongBits(
              other.getHeading()));
      result = result && (
          java.lang.Double.doubleToLongBits(getSpeed())
          == java.lang.Double.doubleToLongBits(
              other.getSpeed()));
      result = result && (getType()
          == other.getType());
      result = result && (getOrigin()
          == other.getOrigin());
      result = result && getId()
          .equals(other.getId());
      result = result && getNatoId()
          .equals(other.getNatoId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getSourceName().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAltitude()));
      hash = (37 * hash) + HEADING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getHeading()));
      hash = (37 * hash) + SPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSpeed()));
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + ORIGIN_FIELD_NUMBER;
      hash = (53 * hash) + getOrigin();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NATO_ID_FIELD_NUMBER;
      hash = (53 * hash) + getNatoId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing the detection data.
     * </pre>
     *
     * Protobuf type {@code DetectionDataRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DetectionDataRequest)
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest.class, com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest.Builder.class);
      }

      // Construct using com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sourceName_ = "";

        latitude_ = 0D;

        longitude_ = 0D;

        altitude_ = 0D;

        heading_ = 0D;

        speed_ = 0D;

        type_ = 0;

        origin_ = 0;

        id_ = "";

        natoId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataRequest_descriptor;
      }

      @java.lang.Override
      public com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest getDefaultInstanceForType() {
        return com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest build() {
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest buildPartial() {
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest result = new com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest(this);
        result.sourceName_ = sourceName_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.altitude_ = altitude_;
        result.heading_ = heading_;
        result.speed_ = speed_;
        result.type_ = type_;
        result.origin_ = origin_;
        result.id_ = id_;
        result.natoId_ = natoId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest) {
          return mergeFrom((com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest other) {
        if (other == com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest.getDefaultInstance()) return this;
        if (!other.getSourceName().isEmpty()) {
          sourceName_ = other.sourceName_;
          onChanged();
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getAltitude() != 0D) {
          setAltitude(other.getAltitude());
        }
        if (other.getHeading() != 0D) {
          setHeading(other.getHeading());
        }
        if (other.getSpeed() != 0D) {
          setSpeed(other.getSpeed());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getOrigin() != 0) {
          setOrigin(other.getOrigin());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getNatoId().isEmpty()) {
          natoId_ = other.natoId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sourceName_ = "";
      /**
       * <code>string sourceName = 1;</code>
       */
      public java.lang.String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceNameBytes() {
        java.lang.Object ref = sourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public Builder setSourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public Builder clearSourceName() {
        
        sourceName_ = getDefaultInstance().getSourceName();
        onChanged();
        return this;
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public Builder setSourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sourceName_ = value;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 3;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 3;</code>
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 3;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 4;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 4;</code>
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 4;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double altitude_ ;
      /**
       * <code>double altitude = 5;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>double altitude = 5;</code>
       */
      public Builder setAltitude(double value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double altitude = 5;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0D;
        onChanged();
        return this;
      }

      private double heading_ ;
      /**
       * <code>double heading = 6;</code>
       */
      public double getHeading() {
        return heading_;
      }
      /**
       * <code>double heading = 6;</code>
       */
      public Builder setHeading(double value) {
        
        heading_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double heading = 6;</code>
       */
      public Builder clearHeading() {
        
        heading_ = 0D;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>double speed = 7;</code>
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>double speed = 7;</code>
       */
      public Builder setSpeed(double value) {
        
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double speed = 7;</code>
       */
      public Builder clearSpeed() {
        
        speed_ = 0D;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>uint32 type = 8;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>uint32 type = 8;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 type = 8;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int origin_ ;
      /**
       * <code>uint32 origin = 9;</code>
       */
      public int getOrigin() {
        return origin_;
      }
      /**
       * <code>uint32 origin = 9;</code>
       */
      public Builder setOrigin(int value) {
        
        origin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 origin = 9;</code>
       */
      public Builder clearOrigin() {
        
        origin_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 16;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 16;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 16;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 16;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 16;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object natoId_ = "";
      /**
       * <code>string nato_id = 18;</code>
       */
      public java.lang.String getNatoId() {
        java.lang.Object ref = natoId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          natoId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nato_id = 18;</code>
       */
      public com.google.protobuf.ByteString
          getNatoIdBytes() {
        java.lang.Object ref = natoId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          natoId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nato_id = 18;</code>
       */
      public Builder setNatoId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        natoId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nato_id = 18;</code>
       */
      public Builder clearNatoId() {
        
        natoId_ = getDefaultInstance().getNatoId();
        onChanged();
        return this;
      }
      /**
       * <code>string nato_id = 18;</code>
       */
      public Builder setNatoIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        natoId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DetectionDataRequest)
    }

    // @@protoc_insertion_point(class_scope:DetectionDataRequest)
    private static final com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest();
    }

    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DetectionDataRequest>
        PARSER = new com.google.protobuf.AbstractParser<DetectionDataRequest>() {
      @java.lang.Override
      public DetectionDataRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DetectionDataRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DetectionDataRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DetectionDataRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.indra.srcc.airsrcc.lib.Detections.DetectionDataRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DetectionDataReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DetectionDataReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sourceName = 1;</code>
     */
    java.lang.String getSourceName();
    /**
     * <code>string sourceName = 1;</code>
     */
    com.google.protobuf.ByteString
        getSourceNameBytes();

    /**
     * <code>uint32 result = 9;</code>
     */
    int getResult();
  }
  /**
   * <pre>
   * The response message containing the ack
   * </pre>
   *
   * Protobuf type {@code DetectionDataReply}
   */
  public  static final class DetectionDataReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DetectionDataReply)
      DetectionDataReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DetectionDataReply.newBuilder() to construct.
    private DetectionDataReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DetectionDataReply() {
      sourceName_ = "";
      result_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DetectionDataReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              sourceName_ = s;
              break;
            }
            case 72: {

              result_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply.class, com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply.Builder.class);
    }

    public static final int SOURCENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object sourceName_;
    /**
     * <code>string sourceName = 1;</code>
     */
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sourceName_ = s;
        return s;
      }
    }
    /**
     * <code>string sourceName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 9;
    private int result_;
    /**
     * <code>uint32 result = 9;</code>
     */
    public int getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSourceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sourceName_);
      }
      if (result_ != 0) {
        output.writeUInt32(9, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSourceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sourceName_);
      }
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply)) {
        return super.equals(obj);
      }
      com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply other = (com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply) obj;

      boolean result = true;
      result = result && getSourceName()
          .equals(other.getSourceName());
      result = result && (getResult()
          == other.getResult());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getSourceName().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message containing the ack
     * </pre>
     *
     * Protobuf type {@code DetectionDataReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DetectionDataReply)
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply.class, com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply.Builder.class);
      }

      // Construct using com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sourceName_ = "";

        result_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.indra.srcc.airsrcc.lib.Detections.internal_static_DetectionDataReply_descriptor;
      }

      @java.lang.Override
      public com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply getDefaultInstanceForType() {
        return com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply build() {
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply buildPartial() {
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply result = new com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply(this);
        result.sourceName_ = sourceName_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply) {
          return mergeFrom((com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply other) {
        if (other == com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply.getDefaultInstance()) return this;
        if (!other.getSourceName().isEmpty()) {
          sourceName_ = other.sourceName_;
          onChanged();
        }
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object sourceName_ = "";
      /**
       * <code>string sourceName = 1;</code>
       */
      public java.lang.String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sourceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSourceNameBytes() {
        java.lang.Object ref = sourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public Builder setSourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sourceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public Builder clearSourceName() {
        
        sourceName_ = getDefaultInstance().getSourceName();
        onChanged();
        return this;
      }
      /**
       * <code>string sourceName = 1;</code>
       */
      public Builder setSourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sourceName_ = value;
        onChanged();
        return this;
      }

      private int result_ ;
      /**
       * <code>uint32 result = 9;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>uint32 result = 9;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 result = 9;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DetectionDataReply)
    }

    // @@protoc_insertion_point(class_scope:DetectionDataReply)
    private static final com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply();
    }

    public static com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DetectionDataReply>
        PARSER = new com.google.protobuf.AbstractParser<DetectionDataReply>() {
      @java.lang.Override
      public DetectionDataReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DetectionDataReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DetectionDataReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DetectionDataReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.indra.srcc.airsrcc.lib.Detections.DetectionDataReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DetectionDataRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DetectionDataRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DetectionDataReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DetectionDataReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020detections.proto\"\274\001\n\024DetectionDataRequ" +
      "est\022\022\n\nsourceName\030\001 \001(\t\022\020\n\010latitude\030\003 \001(" +
      "\001\022\021\n\tlongitude\030\004 \001(\001\022\020\n\010altitude\030\005 \001(\001\022\017" +
      "\n\007heading\030\006 \001(\001\022\r\n\005speed\030\007 \001(\001\022\014\n\004type\030\010" +
      " \001(\r\022\016\n\006origin\030\t \001(\r\022\n\n\002id\030\020 \001(\t\022\017\n\007nato" +
      "_id\030\022 \001(\t\"8\n\022DetectionDataReply\022\022\n\nsourc" +
      "eName\030\001 \001(\t\022\016\n\006result\030\t \001(\r2J\n\tDetection" +
      "\022=\n\rSendDetection\022\025.DetectionDataRequest" +
      "\032\023.DetectionDataReply\"\000B\034\n\032com.indra.src" +
      "c.airsrcc.libb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DetectionDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DetectionDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DetectionDataRequest_descriptor,
        new java.lang.String[] { "SourceName", "Latitude", "Longitude", "Altitude", "Heading", "Speed", "Type", "Origin", "Id", "NatoId", });
    internal_static_DetectionDataReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DetectionDataReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DetectionDataReply_descriptor,
        new java.lang.String[] { "SourceName", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
